## Imports

In [39]:
# Python standards
import numpy as np
import pandas as pd 
import seaborn as sns
import os
import csv
import mygene

# Project Specific
import oggmap
from Bio import Entrez

## Import Data

In [62]:
# Import data files - be able to differentiate between .csv and txt

# Turn input data into pandas tables
def make_table(filepath):
    filename, extension = os.path.splitext(filepath)

    # Convert .csv file to 
    if extension == ".csv":
        table = pd.read_csv(filepath, header=0, index_col=0) 

    # For non .csv files (.txt, .tsv), use Sniffer to automatically detect delimiter type
    elif extension in [".txt", ".tsv"]:
        with open(filepath, 'r') as f1:
            dialect = csv.Sniffer().sniff(f1.readline())
            delimiter = dialect.delimiter
        table = pd.read_csv(filepath, sep=delimiter, header=0, index_col=0)

    # Raise error for non-supported file types
    else:
        raise TypeError("Unsupported format - file must be .csv, .txt, or .tsv")

    # Convert index (row names) to strings and all lowercase - this makes future processing/matching much easier  
    table.index = table.index.map(str)
    table.index = table.index.str.lower()
    
    return table

In [63]:
gse167216 = make_table("GSE167216_Raw_gene_counts_matrix.txt")
gse167216

,I00001,I00002,I00003,I00004,I00005,I00006,I00007,I00008,I00009,I00010,...,I00027,I00028,I00029,I00030,I00031,I00032,I00033,I00034,I00035,I00036
0610007p14rik,858,901,1053,1413,882,704,947,747,1253,928,...,1108,1293,1510,1080,474,1098,857,1187,1572,1111
0610009b22rik,430,515,450,423,395,341,392,449,556,382,...,395,428,515,522,625,487,332,406,440,459
0610009l18rik,14,10,12,9,8,8,12,11,8,5,...,13,7,10,8,10,8,6,7,20,13
0610009o20rik,600,462,559,541,441,268,459,523,594,499,...,475,441,644,479,619,457,437,508,690,378
0610010f05rik,615,439,503,635,448,399,587,592,663,598,...,665,621,733,546,791,572,587,548,701,539
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mt-nd3,7111,12690,9805,8066,6143,6600,4815,9508,8672,9020,...,6218,9097,6992,5356,10781,8872,8342,8975,6406,3930
mt-nd4,21825,29177,26462,33494,32804,16978,15866,33967,30352,29477,...,33113,29928,24068,16664,35913,29747,25289,41894,30768,16901
mt-nd4l,2540,3058,2926,3801,2663,1873,1980,3266,3416,3179,...,3703,3160,2709,1830,3963,3257,2984,3175,3554,2027
mt-nd5,12329,19694,17297,17376,22612,10367,9914,23960,17992,18814,...,21511,15814,15392,10895,23150,15632,16334,31330,17930,9719
mt-nd6,3445,4999,4943,4797,4947,2569,2805,5927,4606,4503,...,4434,3759,4005,2737,4148,3838,3871,5313,3727,2627

In [64]:
gse130970 = make_table("GSE130970_all_sample_salmon_tximport_counts_entrez_gene_ID.csv")
gse130970

,440349.1.X_1,440350.1.X_1,440351.1.X_4,440352.1.X_4,440353.1.X_4,440354.1.X_4,440355.1.X_4,440357.1.X_5,440375.1.X_8,440376.1.X_1,...,440528.1.X_5,440529.1.X_5,440534.1.X_5,440538.1.X_6,440548.1.X_7,449058.1.X_7,449060.1.X_8,449063.1.X_8,449064.1.X_8,449065.1.X_5
entrez_id,,,,,,,,,,,,,,,,,,,,,
1,15968.671716,15623.281336,12255.155811,13328.013047,6906.859596,10556.513029,9997.470671,10990.663466,14610.856238,8831.556786,...,12238.119554,12415.929639,8589.142731,5733.077528,11558.102466,10913.797497,7998.983223,11437.799630,12920.814678,12134.803065
10,1898.629555,1635.901509,1476.107854,1359.128859,847.320724,2195.318504,1546.089761,2677.448665,1094.842543,1251.581809,...,1058.213698,1173.351287,1389.185309,806.590094,1151.900170,1614.468458,1001.914468,1216.451175,1806.864354,1381.227090
100,100.251866,72.353217,67.086243,70.678831,112.301155,47.958587,76.009467,80.078520,57.897957,37.920874,...,34.926947,49.301348,30.347349,22.376608,41.255246,35.518494,38.965886,59.821360,38.398301,28.211496
1000,2969.203686,2997.200299,2547.504384,2625.512441,3644.178703,2485.691808,1216.631804,2240.231843,2569.426700,2756.817348,...,3035.563286,2525.022952,2624.945033,2017.912243,2851.330548,2290.925953,1854.519112,2906.798848,2652.790589,2712.317301
10000,500.447623,398.046887,526.712698,587.135535,907.733154,327.972579,442.578899,408.757014,500.180104,394.381325,...,521.273664,501.178503,296.317901,326.941625,374.622621,405.490427,439.941370,644.346311,704.142490,436.512319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,747.188876,655.162309,491.668494,579.892664,668.498136,477.850890,212.906845,519.450296,496.642412,663.476185,...,648.155921,601.324535,734.041472,549.936611,691.691032,554.669348,433.254671,637.781057,713.836467,567.845280
9991,2211.636662,1761.728905,2105.502024,1730.778374,3392.366337,1700.049695,1052.474125,1839.111546,1679.944401,1464.961920,...,1203.451566,1795.079474,1140.643880,873.682881,1204.299971,1427.748534,1740.054710,1900.554388,1616.047252,1388.998540
9992,107.216755,10.989069,11.856781,27.461816,5.002535,8.081511,31.565271,11.170356,6.987463,10.883135,...,11.684057,16.672927,15.616441,9.101575,24.300868,82.656602,16.833471,13.622228,19.553471,18.538613
9993,940.968292,840.332229,720.596668,892.811641,831.962637,539.511122,241.688583,502.023813,835.562390,804.693391,...,692.968365,922.284074,602.877880,513.974340,819.370846,673.820874,805.285606,1072.053469,806.808277,661.032442
9997,258.067061,268.578830,191.226052,202.827241,246.258101,321.306891,274.532442,282.280184,188.766679,136.680949,...,151.626397,189.138833,145.087856,81.424087,130.152596,161.267812,168.117957,199.101582,176.094994,177.144278

For the dataset GSE130970, the gene IDs are instead recorded as `entrez_id`. We want to map these to gene names.

In [68]:
def convert_entrez(table, genome):
    
    mg = mygene.MyGeneInfo()
    entrez_ID_list = table.index.tolist()
    
    print("Starting MyGene.info query...")
    
    results = mg.querymany(entrez_ID_list,
                           scopes='entrezgene',
                           fields='symbol',
                           species=genome,
                           as_dataframe=True)
    
    # Drop entries without symbols
    results = results.dropna(subset=['symbol'])
    mapping = results[['symbol']]
    mapping = mapping[~mapping.index.duplicated(keep='first')]
    
    # Overwrite original dataframe
    table = table.loc[table.index.intersection(mapping.index)]
    table.index = mapping.loc[table.index, 'symbol']
    
    # Duplicate gene symbols have their expression patterns averaged
    table = table.groupby(table.index).mean()
    
    print(f"Mapped {len(table)} genes to symbols")
    
    return table

In [69]:
gse130970_genes = convert_entrez(gse130970, "human")

Starting MyGene.info query...

159 input query terms found no hit:	['100126582', '100127889', '100128374', '100130285', '100132705', '100133144', '100133301', '1001340

Mapped 19426 genes to symbols

In [53]:
gse130970_genes

,440349.1.X_1,440350.1.X_1,440351.1.X_4,440352.1.X_4,440353.1.X_4,440354.1.X_4,440355.1.X_4,440357.1.X_5,440375.1.X_8,440376.1.X_1,...,440528.1.X_5,440529.1.X_5,440534.1.X_5,440538.1.X_6,440548.1.X_7,449058.1.X_7,449060.1.X_8,449063.1.X_8,449064.1.X_8,449065.1.X_5
symbol,,,,,,,,,,,,,,,,,,,,,
A1BG,15968.671716,15623.281336,12255.155811,13328.013047,6906.859596,10556.513029,9997.470671,10990.663466,14610.856238,8831.556786,...,12238.119554,12415.929639,8589.142731,5733.077528,11558.102466,10913.797497,7998.983223,11437.799630,12920.814678,12134.803065
NAT2,1898.629555,1635.901509,1476.107854,1359.128859,847.320724,2195.318504,1546.089761,2677.448665,1094.842543,1251.581809,...,1058.213698,1173.351287,1389.185309,806.590094,1151.900170,1614.468458,1001.914468,1216.451175,1806.864354,1381.227090
ADA,100.251866,72.353217,67.086243,70.678831,112.301155,47.958587,76.009467,80.078520,57.897957,37.920874,...,34.926947,49.301348,30.347349,22.376608,41.255246,35.518494,38.965886,59.821360,38.398301,28.211496
CDH2,2969.203686,2997.200299,2547.504384,2625.512441,3644.178703,2485.691808,1216.631804,2240.231843,2569.426700,2756.817348,...,3035.563286,2525.022952,2624.945033,2017.912243,2851.330548,2290.925953,1854.519112,2906.798848,2652.790589,2712.317301
AKT3,500.447623,398.046887,526.712698,587.135535,907.733154,327.972579,442.578899,408.757014,500.180104,394.381325,...,521.273664,501.178503,296.317901,326.941625,374.622621,405.490427,439.941370,644.346311,704.142490,436.512319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SLC12A6,747.188876,655.162309,491.668494,579.892664,668.498136,477.850890,212.906845,519.450296,496.642412,663.476185,...,648.155921,601.324535,734.041472,549.936611,691.691032,554.669348,433.254671,637.781057,713.836467,567.845280
PTBP3,2211.636662,1761.728905,2105.502024,1730.778374,3392.366337,1700.049695,1052.474125,1839.111546,1679.944401,1464.961920,...,1203.451566,1795.079474,1140.643880,873.682881,1204.299971,1427.748534,1740.054710,1900.554388,1616.047252,1388.998540
KCNE2,107.216755,10.989069,11.856781,27.461816,5.002535,8.081511,31.565271,11.170356,6.987463,10.883135,...,11.684057,16.672927,15.616441,9.101575,24.300868,82.656602,16.833471,13.622228,19.553471,18.538613
DGCR2,940.968292,840.332229,720.596668,892.811641,831.962637,539.511122,241.688583,502.023813,835.562390,804.693391,...,692.968365,922.284074,602.877880,513.974340,819.370846,673.820874,805.285606,1072.053469,806.808277,661.032442
SCO2,258.067061,268.578830,191.226052,202.827241,246.258101,321.306891,274.532442,282.280184,188.766679,136.680949,...,151.626397,189.138833,145.087856,81.424087,130.152596,161.267812,168.117957,199.101582,176.094994,177.144278

In [ ]:
z